### ISSUE TITLE
Matching on program name but not path

### ISSUE THREAD

**Issue by henryiii** [aklajnert/pytest-subprocess#100]
I've been really enjoying this, but I have had a small pain point: the name must be fully specified. Here's an example:

```python
cmake_path = Path(cmake.CMAKE_BIN_DIR) / "cmake"
fp.register([os.fspath(cmake_path), "--version"], stdout="3.15.0")
```

I tried the nuclear option, but it didn't seem to work (and really isn't what I would normally want to do anyway):

```python
fp.register([fp.any(), "--version"], stdout="3.15.0")
```

A really handy shortcut would be something like this:

```python
fp.register([fp.program("make"), "--version"], stdout="3.15.0")
```

which would only match the final component of the path. Maybe this could even be automatic, such as `"thing"` matching `"/any/thing"` or `shutil.which("thing")` it it's not an absolute path. I'd think the automatic one should require it be on the path - but I'm also interested in a fuzzy one that doesn't require it be on the path.

**Comment by aklajnert** [comment]
I'm surprised that `fp.any()` didn't work, I think it should. Anyway, your proposal sounds like a good idea, I'll think about that. Feel free to submit a PR with this, that would be very welcome.
