### ISSUE TITLE
Cannot raise exception from subprocess

### ISSUE THREAD

**Issue by TilmanK** [aklajnert/pytest-subprocess#11]
I'm trying to test a part of code, in which a call to subprocess.run() raises a PermissionError. How can this be done with the pytest-subprocess fixture?

Thanks for the great piece of code and your support in advance ;)

**Comment by aklajnert** [comment]
Unfortunately, I didn't consider this use case. Potentially this could be done via the callback function, but it is executed in a thread, so there's no way to raise an exception from it.  
I think this is a very useful feature to test for exceptions raised by subprocesses, so I'll work on it.

**Comment by aklajnert** [comment]
@TilmanK I've fixed the callable behavior on the master, but before releasing a new version I want to extend the documentation about how to use them. I'll keep this issue open until the new release.

**Comment by aklajnert** [comment]
I've just released version `0.1.3`, which supports raising exceptions from callbacks. See the [example in documentation](https://pytest-subprocess.readthedocs.io/en/latest/usage.html#using-callbacks), which covers that use case.

**Comment by TilmanK** [comment]
Thanks a lot for the support, will try this now ;)
