### ISSUE TITLE
Fail to mock: 'method' object is not subscriptable

### ISSUE THREAD

**Issue by LecrisUT** [aklajnert/pytest-subprocess#155]
Not sure where the error comes from, but I get a "'method' object is not subscriptable". The code path it was trying to evaluate is:
```python
        def _spawn_process() -> subprocess.Popen[bytes]:
            return subprocess.Popen(
                self.to_popen(),
                cwd=cwd,
                shell=shell,
                env=actual_env.to_popen() if actual_env is not None else None,
                start_new_session=True,
                stdin=subprocess.DEVNULL,
                stdout=subprocess.PIPE,
                stderr=subprocess.STDOUT if join else subprocess.PIPE,
                executable=executable)

        # Spawn the child process
        try:
            process = _spawn_process()
```

**Comment by aklajnert** [comment]
Thanks for reporting the problem, could you please provide a bit bigger example where I could reproduce the issue?

**Comment by LecrisUT** [comment]
I've made a PR for my project where I had these issues. The relevant upstream code that needs to be mocked is:
[`tmt.utils.Command.run`](https://github.com/teemtee/tmt/blob/40ec859781af385ee88d4ba99f8441c4ac580439/tmt/utils.py#L1272-L1282) with the snippet above

**Comment by LecrisUT** [comment]
Forgot to include a link to the PR where I test `pytest-subprocess`: https://github.com/LecrisUT/tmt-cmake/pull/12

**Comment by aklajnert** [comment]
From what I see, your tests are failing due to missing `fp` fixture. Can you paste the whole traceback where it fails with the error you mention?

**Comment by aklajnert** [comment]
I don't really have time to debug that at the moment. It would be very helpful if you prepare a simple, isolated testcase that reproduces the issue, where I could it just copy-paste and quickly run without having to pull your repository and install all the dependencies.

**Comment by LecrisUT** [comment]
[here](https://github.com/lecrisUT/pytest-subprocess-155) is a minimal reproducible
