### ISSUE TITLE
1.5.1 installs stray top-level `tests` package

### ISSUE THREAD

**Issue by mgorny** [aklajnert/pytest-subprocess#161]
The new release installs a stray top-level `tests` package, i.e.:

```
/usr/lib/python3.12/site-packages/tests/__init__.py
/usr/lib/python3.12/site-packages/tests/conftest.py
/usr/lib/python3.12/site-packages/tests/example_script.py
...
```

**Comment by EarthenSky** [comment]
This is a potentially breaking change for any projects which use their own top-level tests package

**Comment by mgorny** [comment]
This is a regression introduced in 1855824e02fe3a72a42b3f8aedef1292d31108c2. Filed #162 to fix it.
