### ISSUE TITLE
Registering a subprocess with a single-argument list or tuple should be the same as a string

### ISSUE THREAD

**Issue by jikamens** [aklajnert/pytest-subprocess#18]
If the process I am invoking in the code I'm testing has no arguments, then I should be able to register it with `fake_process` using either just the same string that is being passed to `check_output`, or as a list or tuple, but right now, only the former works and the latter doesn't.

For example, if this is what I am testing:

```
output = subprocess.check_output("some-command")
```

Then this:

```
fake_process.register_subprocess(("some-command",))
```

and this:

```
fake_process.register_subprocess("some-command")
```

should both work, but only the latter works.

**Comment by aklajnert** [comment]
Right, it should make no difference if subprocess is registered as a string or one-element list. Both should work the same. I'll fix that.
