### ISSUE TITLE
Exceptions are not propagated to callee functions

### ISSUE THREAD

**Issue by sandrotosi** [aklajnert/pytest-subprocess#24]
Hello,
this is an extension of #11.

Say you have a module, with a function:

```
file: mod1.py

def f():
    try:
        x = subprocess.run('asdfasf')
        return True
    except subprocess.CalledProcessError:
        return False
```

and you want to test the except part; i wrote:

```
def test_f(fake_process):
    def callback_exception(process):
        raise subprocess.CalledProcessError(returncode=0, cmd=["bad"])
    with fake_process.context() as nested_process:
        nested_process.register_subprocess(['yadayada', 'lallalla'], callback=callback_exception)
        y = mod1.f()
        assert not y
```

but turns out `subprocess.run` gets executed just fine in mod1.f but just with a `returncode=None`, which is not what i'd expect

it would be great if, instead of using a callback function, we could have an extra argument to `register_subprocess` to actually make it raise an exception, even if you're testing code not in the current module.

Thanks!

**Comment by aklajnert** [comment]
You can use the callback function to change exit code:  
```python
def callback_function(process):
    returncode = 0
    process.returncode = returncode
    raise subprocess.CalledProcessError(returncode=returncode, cmd=self.args)
```

I'm not sure how the extra argument to `register_subprocess` should look like. How do you imagine the usage?

**Comment by sandrotosi** [comment]
I dont want to change the returncode, i want to get an exception raised :) (my code already checks for returncode == or !=0, so that's really not what i want).

i guess close to callback so:

```
register_subprocess(...
    exception_class = exc_class_name,
    exception_kwargs = {}
)
```

where you pass in the exception class you want to raise and an optional set of arguments to pass to it

**Comment by aklajnert** [comment]
Actually, for `subprocess.run()` you don't have to use a callback to raise the `CalledProcessError`.  
Just set the `returncode` argument for `register_subprocess` method to a non-zero value, and run `subprocess.run()` with `check=True` (see [subprocess code](https://github.com/python/cpython/blob/master/Lib/subprocess.py#L524)).  

That's a better approach as it bases on the underlying `subprocess` API. If the `subprocess.run()` behavior will change in the future, your tests you won't get false positives from your tests.

**Comment by sandrotosi** [comment]
ok, let's put aside `run()` for a moment, as it was mostly an example, what about `check_output()`?

**Comment by sandrotosi** [comment]
or what if want to test a function that handles this:

```
$ python3 -c "import subprocess; subprocess.run('asdf')"
...
FileNotFoundError: [Errno 2] No such file or directory: 'asdf': 'asdf'
```

**Comment by aklajnert** [comment]
`check_output()` internally uses `run()` with `check=True` ([see code](https://github.com/python/cpython/blob/master/Lib/subprocess.py#L420)), so it'll also raise an exception for non-zero exit code.

**Comment by aklajnert** [comment]
Oh, now I see it - there's actually a bug. In my plugin only `Popen.wait()` raises an exception, but the same should happen for `Popen.communicate()`.  
The exception should be raised further by the `subprocess.run()`.

**Comment by aklajnert** [comment]
There was a bug with that in the previous version - are you sure you're using the latest one (`0.1.4`)?

In the following example, the exception is raised correctly:  
```python
def test_raise_exception(fake_process):
    def callback_function(process):
        raise subprocess.CalledProcessError(process.returncode, process.args)

    fake_process.keep_last_process(True)
    fake_process.register_subprocess(["test"], callback=callback_function)

    with pytest.raises(subprocess.CalledProcessError):
        process = subprocess.Popen(["test"])
        process.wait()

    with pytest.raises(subprocess.CalledProcessError):
        subprocess.run(["test"])
```

**Comment by sandrotosi** [comment]
yeah, i'm using 0.1.4; i needed to rework my code to make this work, but i guess that's ok -- thanks!
