### ISSUE TITLE
pytest_subprocess.utils.Command is not iterable

### ISSUE THREAD

**Issue by GinoCubeddu** [aklajnert/pytest-subprocess#31]
Hello,

I am having troubles with one of our mocked processes.

Specifically the [args attribute](https://github.com/aklajnert/pytest-subprocess/blob/master/pytest_subprocess/core.py#L48).

I'm running into a problem where instead of getting a tuple from `.args` we get an object of type `pytest_subprocess.utils.Command`. We need to iterate over `args` which should be a tuple but your Command class which was introduced in `1.0.0` is not iterable.

When you print `p.args` (where `p` is the returned process) it prints what looks to be a tuple but is not. The tuple itself is in `p.args.command`. 

See the below:

```
============================
contents and type of p.args
============================
('command', 'being', 'run', 'plus', 'passed', 'args')
<class 'pytest_subprocess.utils.Command'>
============================
contents and type of p.args.command
============================
('command', 'being', 'run', 'plus', 'passed', 'args')
<class 'tuple'>
```

`pytest_subprocess.utils.Command` can be made iterable and solve this problem if an `__iter__` method is added to the [Command class](https://github.com/aklajnert/pytest-subprocess/blob/master/pytest_subprocess/utils.py#L16), adding the below locally fixes the problem:

```python
def __iter__(self):
      return iter(self.command)
```

Kind Regards
Gino Cubeddu

**Comment by aklajnert** [comment]
Thanks @GinoCubeddu for reporting this issue. I've indeed forgotten to implement the `__iter__()` method.  
Feel free to submit a PR for this if you like, or I'll deal with it later this week.
