### ISSUE TITLE
Allow any number of occurrences

### ISSUE THREAD

**Issue by calebho** [aklajnert/pytest-subprocess#40]
Currently a finite number of occurrences per command is allowed, e.g. [for `pass_command`](https://github.com/aklajnert/pytest-subprocess/blob/0d5f06c7b8656e6da0a9e61fcbfff8f430bbae46/pytest_subprocess/core.py#L412-L423). Would be nice if an arbitrary number of occurrences is supported.

Seems like currently this behavior is [implemented using a deque](https://github.com/aklajnert/pytest-subprocess/blob/0d5f06c7b8656e6da0a9e61fcbfff8f430bbae46/pytest_subprocess/core.py#L358-L360). Didn't read the code very thoroughly so I'm not sure how the deque is used, but one approach could be storing an iterator instead which would support an infinite iterator e.g. via `itertools.repeat`.

**Comment by calebho** [comment]
A nice side effect is that it should make the implementation more memory efficient as all the values won't be loaded into memory at once.

**Comment by aklajnert** [comment]
You can achieve this behavior by using `fake_process.keep_last_process(True)`:  

```python
def test_multiple_executions_real_process(fake_process):
    command = ["python", "example_script.py"]
    fake_process.register_subprocess(
        command,
        stdout="faked",
    )
    fake_process.pass_command(command)
    fake_process.keep_last_process(True)

    assert subprocess.check_output(command) == b"faked"
    assert subprocess.check_output(command) != b"faked"
    assert subprocess.check_output(command) != b"faked"
    assert subprocess.check_output(command) != b"faked"
    assert subprocess.check_output(command) != b"faked"
    assert subprocess.check_output(command) != b"faked"
```

Let me know if that's what you need.

**Comment by calebho** [comment]
Awesome that works; thanks!
