### ISSUE TITLE
Type error because List is invariant

### ISSUE THREAD

**Issue by calebho** [aklajnert/pytest-subprocess#41]
Version info:
```
mypy                    0.812
pytest-subprocess       1.1.0
```
Error:
```
main.py:34: error: Argument 1 to "register_subprocess" of "FakeProcess" has incompatible type "List[str]"; expected "Union[List[Union[str, Any]], Tuple[Union[str, Any], ...], str, Command]"
main.py:34: note: "List" is invariant -- see http://mypy.readthedocs.io/en/latest/common_issues.html#variance
main.py:34: note: Consider using "Sequence" instead, which is covariant
main.py:34: error: Argument "stdout" to "register_subprocess" of "FakeProcess" has incompatible type "List[str]"; expected "Union[str, bytes, List[Union[str, bytes]], Tuple[Union[str, bytes], ...], None]"
```
https://mypy-play.net/?mypy=latest&python=3.9&gist=89232479f9811be76ee54460a5f1a895

Fixable if you annotate the arguments as `List[Union[str, bytes]]`.

Does `register_subprocess` really require the ability to mutate the input list? If it only needs read-only access, then using `Sequence` would be helpful to avoid the unnecessary upcast.

**Comment by aklajnert** [comment]
Thank you for reporting. From what I remember, there's no need to mutate the input list, so using `Sequence` should be OK here.  
Feel free to file a PR, if not, I'll deal with it soon.

**Comment by calebho** [comment]
I don't currently have time to submit a PR and it's not a serious issue so I'll await your fix. Thanks!
