### ISSUE TITLE
allow_unregistered(True) in one test case affects other test cases

### ISSUE THREAD

**Issue by romanek-adam** [aklajnert/pytest-subprocess#46]
Today I discovered that `fake_process.allow_unregistered(True)` in one test case applies to / affects all following test cases.

Here's a minimal reproducible example:
```python
import subprocess

import pytest
import pytest_subprocess


def test_1(fake_process):
    with pytest.raises(pytest_subprocess.ProcessNotRegisteredError):
        subprocess.run(["ls"])


def test_2(fake_process):
    fake_process.allow_unregistered(True)


def test_3(fake_process):
    with pytest.raises(pytest_subprocess.ProcessNotRegisteredError):
        subprocess.run(["ls"])
```

Note `test_1` and `test_3` are exactly the same. Unfortunately when run one after another `test_1` passes, while `test_3` fails.

Tested on Python 3.8.10, pytest 6.2.4 and pytest_subprocess 1.1.1.

**Comment by aklajnert** [comment]
Thanks for reporting. I see that `keep_last_process()` has the same issue. I'll fix it soon.

**Comment by romanek-adam** [comment]
Thanks @aklajnert for the fix and a very quick response :)
