### ISSUE TITLE
Support for terminate, kill, send_signal

### ISSUE THREAD

**Issue by blalor** [aklajnert/pytest-subprocess#54]
The `terminate()`, `kill()`, and `send_signal()` methods of `subprocess.Popen` don't appear to be implemented in `FakePopen`. Is this intentional?

**Comment by aklajnert** [comment]
It seems that I've overlooked these methods. It's not intentional, I think they should be implemented (at least as stubs) in `FakePopen`.  
Thanks for pointing that out, I'll work on it soon.
