### ISSUE TITLE
asyncio.create_subprocess_exec fails if *args used. 

### ISSUE THREAD

**Issue by Samthos** [aklajnert/pytest-subprocess#60]
Python: 3.8.12
pytest-subprocess: 1.3.1

The function signature for for `asyncio.create_subprocess_exec` takes an executable and *args as arguments. 

If I register a fake_process to mock a call with just an executable, the test will run fine. 
If I register a fake_process that needs to handle arguments, the test fails with a TypeError that says for example:

`async_shell() takes 2 positional arguments but 5 were given`

I've attached an MWE that demonstrates this. Please change .txt to .py. Github would not let me upload .py files. 

main.py should run execute when called with python3
text.py will produce two passes and a failure. The failing test will be `test_exec_args`.

[main.txt](https://github.com/aklajnert/pytest-subprocess/files/7478446/main.txt)
[test.txt](https://github.com/aklajnert/pytest-subprocess/files/7478447/test.txt)

**Comment by aklajnert** [comment]
Oh, right - how could I miss that these functions are different?
It is a bug, thank you for reporting. I'll try to fix it soon.

**Comment by aklajnert** [comment]
@Samthos - this is now fixed and released in version `1.3.2`, please give it a try.
